### ISSUE TITLE
Bug report: BITCOIN not updating

### ISSUE THREAD

**Issue by mbcooper** [matextrem/streamdeck-tickertap#2] opened 2024-05-28 12:24 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by matextrem** [comment] 2024-05-28 14:35
@mbcooper Thanks for your report! 

There were some changes in the coinmarketcap site that was causing cryptocurrencies not being fetched properly. I created a new plugin version with the fix. Could you please [download](https://github.com/matextrem/streamdeck-tickertap/releases/tag/v1.1.1) it and let me know if the issue is now fixed? Thanks!

**Comment by mbcooper** [comment] 2024-05-28 16:50
works ok!

--mike

**Closed** 2024-05-28 20:08 UTC
Labels: bug
